/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2021-02-10T21:07:13. Do not modify directly. */

#include "buildinfo.h"

const struct buildinfo* nsfminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = { 
        .project_name = { "PROJECT_NAME" } ,
        .project_version = { "PROJECT_VERSION" } ,
        .project_name_with_version = { "PROJECT_NAME_VERSION" } ,
        .git_commit_hash = { "COMMIT" } ,
        .system_name = { "SYSTEM_NAME" } ,
        .system_processor = { "SYSTEM_PROCESSOR" } ,
        .compiler_id = { "COMPILER_ID" } ,
        .compiler_version = { "COMPILER_VERSION" } ,
        .build_type = { "BUILD_TYPE" }
    };
    return &buildinfo;
}
